export interface IngredientInfo {
  ingredient_name: string;
  description: string;
  benefits: string[];
  best_for: string[];
  usage_rate: string;
  category: string;
  ph_notes: string | null;
  cautions: string | null;
}

export const INGREDIENT_DB: Record<string, IngredientInfo> = {
  'shea butter': {
    ingredient_name: 'Shea Butter',
    description: 'A fat extracted from the nut of the African shea tree. Rich in fatty acids and vitamins, solid at room temperature and melts on contact with skin.',
    benefits: ['Deep moisturizing', 'Anti-inflammatory', 'Promotes skin elasticity', 'Soothes dry and irritated skin'],
    best_for: ['Dry skin', 'Sensitive skin', 'Eczema-prone skin'],
    usage_rate: '2–30% in lotions, up to 100% as a straight butter',
    category: 'Occlusive / Emollient',
    ph_notes: null,
    cautions: 'May feel heavy in high concentrations for oily skin types.',
  },
  'jojoba oil': {
    ingredient_name: 'Jojoba Oil',
    description: 'A liquid wax extracted from the seed of the jojoba plant. Technically a wax ester, it closely mimics the skin\'s natural sebum and is very stable.',
    benefits: ['Balances oil production', 'Non-comedogenic', 'Long shelf life', 'Lightweight moisturizer'],
    best_for: ['All skin types', 'Acne-prone skin', 'Oily skin'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: null,
  },
  'niacinamide': {
    ingredient_name: 'Niacinamide (Vitamin B3)',
    description: 'A water-soluble form of vitamin B3. One of the most well-researched skincare actives with excellent tolerability.',
    benefits: ['Reduces pore appearance', 'Controls sebum', 'Brightens skin tone', 'Strengthens skin barrier', 'Reduces redness'],
    best_for: ['Oily skin', 'Acne-prone skin', 'Hyperpigmentation', 'Aging skin'],
    usage_rate: '2–10%',
    category: 'Active',
    ph_notes: 'Stable between pH 5–7.',
    cautions: 'At concentrations above 10% may cause flushing in sensitive individuals.',
  },
  'glycerin': {
    ingredient_name: 'Glycerin (Glycerol)',
    description: 'A simple polyol compound that occurs naturally in all living things. One of the most effective and widely used humectants in cosmetics.',
    benefits: ['Draws moisture into skin', 'Improves skin barrier', 'Enhances product spreadability', 'Non-irritating'],
    best_for: ['All skin types', 'Dehydrated skin', 'Sensitive skin'],
    usage_rate: '1–10% in leave-on products',
    category: 'Humectant',
    ph_notes: null,
    cautions: 'At very high concentrations (above 30%) can draw moisture out of skin in low-humidity environments.',
  },
  'hyaluronic acid': {
    ingredient_name: 'Hyaluronic Acid (Sodium Hyaluronate)',
    description: 'A naturally occurring polysaccharide capable of holding up to 1000x its weight in water, making it an exceptional humectant.',
    benefits: ['Intense hydration', 'Plumps fine lines', 'Lightweight feel', 'Compatible with most ingredients'],
    best_for: ['All skin types', 'Dehydrated skin', 'Aging skin'],
    usage_rate: '0.1–2%',
    category: 'Humectant',
    ph_notes: 'Most effective between pH 5–8.',
    cautions: 'Apply to damp skin and seal with an occlusive to prevent moisture loss in dry climates.',
  },
  'btms-50': {
    ingredient_name: 'BTMS-50 (Behentrimonium Methosulfate)',
    description: 'A conditioning emulsifying wax derived from rapeseed oil. Creates rich, creamy emulsions popular for hair and skin.',
    benefits: ['Effective emulsifier', 'Adds conditioning', 'Creates stable emulsions', 'Imparts silky skin feel'],
    best_for: ['Lotions', 'Creams', 'Hair conditioners'],
    usage_rate: '4–8% as primary emulsifier',
    category: 'Emulsifier',
    ph_notes: null,
    cautions: null,
  },
  'cetyl alcohol': {
    ingredient_name: 'Cetyl Alcohol',
    description: 'A fatty alcohol derived from palm or coconut oil. A waxy solid that thickens and conditions — not a drying alcohol.',
    benefits: ['Thickens formulas', 'Adds emolliency', 'Improves texture', 'Stabilizes emulsions'],
    best_for: ['Creams', 'Lotions', 'Conditioners'],
    usage_rate: '1–6%',
    category: 'Emollient / Thickener',
    ph_notes: null,
    cautions: null,
  },
  'vitamin e': {
    ingredient_name: 'Vitamin E (Tocopherol)',
    description: 'A fat-soluble antioxidant naturally found in many plant oils. Used to extend shelf life and provide skin benefits.',
    benefits: ['Antioxidant protection', 'Extends product shelf life', 'Moisturizing', 'Supports skin healing'],
    best_for: ['Dry skin', 'Aging skin', 'Oil-based formulas'],
    usage_rate: '0.5–1%',
    category: 'Antioxidant',
    ph_notes: null,
    cautions: 'Can cause allergic reactions in some individuals at higher concentrations.',
  },
  'aloe vera': {
    ingredient_name: 'Aloe Vera Gel',
    description: 'A gel extracted from the leaves of the aloe plant. Contains polysaccharides, vitamins, and minerals with well-documented soothing properties.',
    benefits: ['Soothes irritated skin', 'Lightweight hydration', 'Anti-inflammatory', 'Cooling effect'],
    best_for: ['Sensitive skin', 'Sunburned skin', 'Oily skin'],
    usage_rate: '2–98%',
    category: 'Humectant / Soothing Agent',
    ph_notes: 'pH around 4.5–5.5.',
    cautions: 'Some people have aloe allergies — patch test recommended.',
  },
  'sodium percarbonate': {
    ingredient_name: 'Sodium Percarbonate',
    description: 'An oxidizing agent that releases hydrogen peroxide when dissolved in water. Used as an oxygen bleach in laundry formulations.',
    benefits: ['Effective stain removal', 'Brightens whites', 'Kills bacteria and mold', 'Breaks down to water and soda ash'],
    best_for: ['Laundry powder', 'Cleaning products', 'Whitening formulas'],
    usage_rate: '10–30% in laundry powder',
    category: 'Oxidizing Agent / Bleach',
    ph_notes: 'Creates alkaline solution when dissolved.',
    cautions: 'Keep dry — moisture activates it. Not for use on wool or silk. Irritating to eyes.',
  },
  'washing soda': {
    ingredient_name: 'Washing Soda (Sodium Carbonate)',
    description: 'A highly alkaline salt used as a water softener and cleaning booster. Key ingredient in DIY laundry formulas.',
    benefits: ['Softens hard water', 'Boosts cleaning power', 'Removes grease and stains', 'Inexpensive'],
    best_for: ['Laundry powder', 'Cleaning products'],
    usage_rate: '30–50% in laundry powder',
    category: 'Alkaline Builder',
    ph_notes: 'Highly alkaline — pH around 11.',
    cautions: 'Irritating to skin and eyes. Not for delicate fabrics. Do not confuse with baking soda.',
  },
  'slsa': {
    ingredient_name: 'SLSA (Sodium Lauryl Sulfoacetate)',
    description: 'A mild, plant-derived surfactant that creates a fluffy lather. Much gentler than SLS, derived from coconut and palm oils.',
    benefits: ['Gentle cleansing', 'Rich fluffy lather', 'Less irritating than SLS', 'Safe for sensitive skin'],
    best_for: ['Bath bombs', 'Bubble bath', 'Gentle cleansers', 'Laundry powder'],
    usage_rate: '5–25%',
    category: 'Surfactant',
    ph_notes: null,
    cautions: 'Fine powder — use a mask when handling to avoid inhaling.',
  },
  'coconut oil': {
    ingredient_name: 'Coconut Oil',
    description: 'A saturated fat extracted from fresh coconut meat. High in lauric acid with antimicrobial properties, solid at room temperature.',
    benefits: ['Moisturizing', 'Antimicrobial', 'Creates hard bar soap', 'Good lather in soap making'],
    best_for: ['Soap making', 'Hair care', 'Body products'],
    usage_rate: '15–30% in soap, 1–10% in skin products',
    category: 'Occlusive / Emollient',
    ph_notes: null,
    cautions: 'Comedogenic rating of 4 — can clog pores for acne-prone skin. Fractionated coconut oil is lighter and non-comedogenic.',
  },
  'castile soap': {
    ingredient_name: 'Castile Soap',
    description: 'A vegetable-based soap made with plant oils, free of synthetic detergents. Versatile for cleaning and personal care.',
    benefits: ['Gentle cleansing', 'Biodegradable', 'Versatile', 'Free of synthetic detergents'],
    best_for: ['Sensitive skin', 'Natural cleaning', 'DIY household products'],
    usage_rate: 'As needed — used as a base',
    category: 'Surfactant / Cleanser',
    ph_notes: 'Highly alkaline — pH 9–11. Do not mix with acidic ingredients like vinegar.',
    cautions: 'Mixing with acids will unsaponify the soap and cause curdling.',
  },
  'sunflower oil': {
    ingredient_name: 'Sunflower Seed Oil',
    description: 'A light, non-greasy oil high in linoleic acid. One of the best oils for sensitive and acne-prone skin.',
    benefits: ['High linoleic acid content', 'Lightweight', 'Supports skin barrier', 'Non-comedogenic'],
    best_for: ['Sensitive skin', 'Acne-prone skin', 'Dry skin'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: 'Shorter shelf life than some oils — add vitamin E to extend.',
  },
  'beeswax': {
    ingredient_name: 'Beeswax',
    description: 'A natural wax produced by honeybees. Used to thicken, provide structure, and create a protective barrier on skin.',
    benefits: ['Thickens and hardens formulas', 'Creates protective barrier', 'Locks in moisture', 'Natural preservative properties'],
    best_for: ['Lip balm', 'Body butter', 'Salves', 'Lotion bars'],
    usage_rate: '5–30% depending on desired hardness',
    category: 'Wax / Thickener',
    ph_notes: null,
    cautions: 'Not vegan. Can feel heavy on skin at high concentrations.',
  },
  'colloidal oatmeal': {
    ingredient_name: 'Colloidal Oatmeal',
    description: 'Finely milled oats processed to disperse in water. FDA-approved skin protectant with anti-itch and soothing properties.',
    benefits: ['Soothes itch and irritation', 'Anti-inflammatory', 'Gentle exfoliation', 'Strengthens skin barrier'],
    best_for: ['Eczema', 'Sensitive skin', 'Dry itchy skin'],
    usage_rate: '0.5–5%',
    category: 'Soothing Agent / Skin Protectant',
    ph_notes: null,
    cautions: 'Must be finely milled to disperse properly. Avoid if oat allergy is a concern.',
  },
  'panthenol': {
    ingredient_name: 'Panthenol (Pro-Vitamin B5)',
    description: 'The alcohol form of pantothenic acid. Converts to vitamin B5 in skin and is prized for moisturizing and healing properties.',
    benefits: ['Deep moisturizing', 'Promotes wound healing', 'Reduces inflammation', 'Improves skin elasticity'],
    best_for: ['Dry skin', 'Damaged skin', 'Hair care'],
    usage_rate: '0.5–5%',
    category: 'Humectant / Skin Conditioning Agent',
    ph_notes: 'Stable between pH 4–7.',
    cautions: null,
  },
  'allantoin': {
    ingredient_name: 'Allantoin',
    description: 'A naturally occurring compound found in comfrey root. Known for soothing skin and accelerating cell regeneration.',
    benefits: ['Soothes and calms skin', 'Promotes cell turnover', 'Anti-irritant', 'Softens keratin'],
    best_for: ['Sensitive skin', 'Acne-prone skin', 'After-sun care'],
    usage_rate: '0.1–2%',
    category: 'Soothing Agent',
    ph_notes: 'Dissolves better in warm water.',
    cautions: null,
  },
  'citric acid': {
    ingredient_name: 'Citric Acid',
    description: 'A weak organic acid found naturally in citrus fruits. Used primarily to adjust pH and as a preservative booster.',
    benefits: ['pH adjustment', 'Preservative booster', 'Mild AHA exfoliant at higher concentrations', 'Chelating agent'],
    best_for: ['pH adjustment in all formulas', 'Bath bombs', 'Toners'],
    usage_rate: 'As needed for pH adjustment, 1–10% as active',
    category: 'pH Adjuster / AHA',
    ph_notes: 'Very acidic — use in small amounts to lower pH.',
    cautions: 'Do not mix directly with castile soap or other alkaline ingredients without diluting first.',
  },
  'sweet almond oil': {
    ingredient_name: 'Sweet Almond Oil',
    description: 'A light, versatile oil pressed from almonds. Rich in oleic and linoleic acids, excellent for skin softening.',
    benefits: ['Softens and conditions skin', 'Lightweight absorption', 'Rich in vitamin E', 'Good for hair and skin'],
    best_for: ['Dry skin', 'Normal skin', 'Massage oils', 'Body lotions'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: 'Avoid if nut allergy is present.',
  },
  'rosehip oil': {
    ingredient_name: 'Rosehip Seed Oil',
    description: 'A dry, fast-absorbing oil pressed from rose seeds. High in vitamin A (retinol precursor) and linoleic acid, prized for anti-aging benefits.',
    benefits: ['Anti-aging', 'Brightening', 'Reduces hyperpigmentation', 'Supports skin regeneration'],
    best_for: ['Aging skin', 'Hyperpigmentation', 'Dry skin', 'Scarring'],
    usage_rate: '1–100%',
    category: 'Emollient / Active',
    ph_notes: null,
    cautions: 'Oxidizes quickly — store in a dark bottle and add vitamin E to extend shelf life.',
  },
  'argan oil': {
    ingredient_name: 'Argan Oil',
    description: 'A luxurious oil pressed from the kernels of the Moroccan argan tree. Rich in oleic acid and vitamin E, excellent for hair and skin.',
    benefits: ['Deeply nourishing', 'Anti-aging', 'Tames frizz in hair', 'Non-greasy finish'],
    best_for: ['Dry and damaged hair', 'Aging skin', 'Dry skin', 'Nail care'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: null,
  },
  'castor oil': {
    ingredient_name: 'Castor Oil',
    description: 'A thick, viscous oil from the castor bean plant. High in ricinoleic acid, a unique fatty acid with humectant and conditioning properties.',
    benefits: ['Draws moisture to skin', 'Thickens formulas', 'Promotes hair growth', 'Adds gloss to lip products'],
    best_for: ['Lip balm', 'Hair growth serums', 'Soap making (adds lather)', 'Eyelash serums'],
    usage_rate: '5–20% in skin/hair products, 5–10% in soap',
    category: 'Humectant / Emollient',
    ph_notes: null,
    cautions: 'Very thick — use in combination with lighter oils. Can feel sticky at high percentages.',
  },
  'avocado oil': {
    ingredient_name: 'Avocado Oil',
    description: 'A rich, heavy oil pressed from avocado flesh. Very high in oleic acid and vitamins A, D, and E.',
    benefits: ['Deeply penetrating', 'Nourishing for very dry skin', 'Anti-inflammatory', 'Good for mature skin'],
    best_for: ['Very dry skin', 'Aging skin', 'Damaged hair', 'Rich body butters'],
    usage_rate: '2–20%',
    category: 'Emollient',
    ph_notes: null,
    cautions: 'Heavy feel — blend with lighter oils for leave-on skin products.',
  },
  'hemp seed oil': {
    ingredient_name: 'Hemp Seed Oil',
    description: 'A lightweight oil pressed from hemp seeds. Has an ideal 3:1 ratio of omega-6 to omega-3 fatty acids, excellent for skin balance.',
    benefits: ['Balances skin', 'Anti-inflammatory', 'Non-comedogenic', 'Strengthens skin barrier'],
    best_for: ['Oily skin', 'Acne-prone skin', 'Eczema', 'Sensitive skin'],
    usage_rate: '1–100%',
    category: 'Emollient',
    ph_notes: null,
    cautions: 'Oxidizes fairly quickly — store refrigerated or add antioxidants.',
  },
  'emulsifying wax nf': {
    ingredient_name: 'Emulsifying Wax NF',
    description: 'A blend of cetearyl alcohol and polysorbate 60. A reliable, easy-to-use emulsifier for beginners making lotions.',
    benefits: ['Stable emulsions', 'Easy to use', 'Widely available', 'Works with many oils'],
    best_for: ['Body lotions', 'Face creams', 'Beginner formulas'],
    usage_rate: '5–10%',
    category: 'Emulsifier',
    ph_notes: null,
    cautions: null,
  },
  'stearic acid': {
    ingredient_name: 'Stearic Acid',
    description: 'A saturated fatty acid derived from plant or animal fats. Used to harden and stabilize formulas.',
    benefits: ['Thickens and hardens formulas', 'Stabilizes emulsions', 'Improves skin feel', 'Creates pearlescent effect in soap'],
    best_for: ['Lotions', 'Creams', 'Soap making', 'Deodorant bars'],
    usage_rate: '1–10%',
    category: 'Emollient / Thickener',
    ph_notes: null,
    cautions: null,
  },
  'zinc pca': {
    ingredient_name: 'Zinc PCA',
    description: 'A zinc salt of pyrrolidone carboxylic acid (PCA). A humectant with sebum-regulating properties.',
    benefits: ['Controls sebum production', 'Antimicrobial', 'Humectant', 'Reduces acne-causing bacteria'],
    best_for: ['Oily skin', 'Acne-prone skin', 'Combination skin'],
    usage_rate: '0.5–2%',
    category: 'Active / Sebum Regulator',
    ph_notes: null,
    cautions: null,
  },
  'kojic acid': {
    ingredient_name: 'Kojic Acid',
    description: 'A naturally derived ingredient from fermented rice. Inhibits melanin production, used to brighten and even skin tone.',
    benefits: ['Brightening', 'Reduces hyperpigmentation', 'Evens skin tone', 'Antifungal properties'],
    best_for: ['Hyperpigmentation', 'Dark spots', 'Uneven skin tone', 'Brightening serums'],
    usage_rate: '0.5–4%',
    category: 'Active / Brightening Agent',
    ph_notes: 'Most effective at pH 3.5–5.',
    cautions: 'Can cause irritation in sensitive individuals. Use sunscreen when using kojic acid products.',
  },
  'vitamin c': {
    ingredient_name: 'Vitamin C (L-Ascorbic Acid)',
    description: 'A potent antioxidant active ingredient. Brightens skin, stimulates collagen production, and protects against environmental damage.',
    benefits: ['Brightening', 'Antioxidant protection', 'Stimulates collagen', 'Fades dark spots'],
    best_for: ['Hyperpigmentation', 'Aging skin', 'Dull skin', 'Sun damage'],
    usage_rate: '5–20%',
    category: 'Active / Antioxidant',
    ph_notes: 'Most effective at pH 2.5–3.5. Very unstable — oxidizes quickly.',
    cautions: 'Highly unstable — use ascorbic acid derivatives like ascorbyl glucoside for more stability. Do not combine with niacinamide at high concentrations.',
  },
  'retinol': {
    ingredient_name: 'Retinol (Vitamin A)',
    description: 'A vitamin A derivative that accelerates skin cell turnover. One of the most evidence-backed anti-aging ingredients available.',
    benefits: ['Reduces fine lines and wrinkles', 'Speeds cell turnover', 'Unclogs pores', 'Fades hyperpigmentation'],
    best_for: ['Aging skin', 'Acne-prone skin', 'Hyperpigmentation'],
    usage_rate: '0.01–1%',
    category: 'Active / Anti-Aging',
    ph_notes: 'Stable at pH 4.5–5.5.',
    cautions: 'Can cause dryness, peeling, and purging. Start low and build up. Avoid during pregnancy. Always use SPF when using retinol.',
  },
  'salicylic acid': {
    ingredient_name: 'Salicylic Acid (BHA)',
    description: 'A beta hydroxy acid (BHA) derived from willow bark. Oil-soluble, making it uniquely able to penetrate pores.',
    benefits: ['Unclogs pores', 'Reduces blackheads and whiteheads', 'Exfoliates inside pores', 'Anti-inflammatory'],
    best_for: ['Acne-prone skin', 'Oily skin', 'Blackheads', 'Clogged pores'],
    usage_rate: '0.5–2%',
    category: 'Active / BHA Exfoliant',
    ph_notes: 'Most effective at pH 3–4.',
    cautions: 'Can be drying. Start with lower concentrations. Avoid if aspirin-sensitive.',
  },
  'azelaic acid': {
    ingredient_name: 'Azelaic Acid',
    description: 'A dicarboxylic acid naturally found in grains. Multitasking active that targets acne, rosacea, and hyperpigmentation.',
    benefits: ['Reduces acne', 'Brightens skin', 'Reduces rosacea redness', 'Antibacterial', 'Fades post-acne marks'],
    best_for: ['Acne-prone skin', 'Rosacea', 'Hyperpigmentation', 'Sensitive skin'],
    usage_rate: '5–20%',
    category: 'Active / Multitasking',
    ph_notes: 'Most effective at pH 4–5.',
    cautions: 'Generally well tolerated but can cause tingling on sensitive skin.',
  },
  'lactic acid': {
    ingredient_name: 'Lactic Acid (AHA)',
    description: 'A gentle alpha hydroxy acid derived from milk. Exfoliates the skin surface and has additional humectant properties.',
    benefits: ['Gentle chemical exfoliation', 'Brightening', 'Humectant', 'Improves skin texture'],
    best_for: ['Sensitive skin (gentlest AHA)', 'Dry skin', 'Dull skin', 'Beginners to acids'],
    usage_rate: '2–15%',
    category: 'Active / AHA Exfoliant',
    ph_notes: 'Most effective at pH 3–4.',
    cautions: 'Increases sun sensitivity — always use SPF. Can cause tingling.',
  },
  'glycolic acid': {
    ingredient_name: 'Glycolic Acid (AHA)',
    description: 'The smallest alpha hydroxy acid, derived from sugarcane. Penetrates skin most deeply of all AHAs for potent exfoliation.',
    benefits: ['Powerful exfoliation', 'Stimulates collagen', 'Brightening', 'Reduces fine lines'],
    best_for: ['Normal to oily skin', 'Aging skin', 'Hyperpigmentation', 'Textured skin'],
    usage_rate: '2–15% in leave-on, up to 70% in professional peels',
    category: 'Active / AHA Exfoliant',
    ph_notes: 'Most effective at pH 3–4.',
    cautions: 'Strongest AHA — can cause irritation and peeling. Always use SPF. Not recommended for sensitive skin.',
  },
  'xanthan gum': {
    ingredient_name: 'Xanthan Gum',
    description: 'A polysaccharide produced by bacterial fermentation. Used as a natural thickener and stabilizer in water-based formulas.',
    benefits: ['Thickens water-based formulas', 'Stabilizes emulsions', 'Creates gel-like texture', 'Natural and biodegradable'],
    best_for: ['Serums', 'Gels', 'Toners', 'Cleansers'],
    usage_rate: '0.1–1%',
    category: 'Thickener / Stabilizer',
    ph_notes: 'Stable across wide pH range.',
    cautions: 'Can be difficult to disperse — mix with glycerin first to prevent clumping.',
  },
  'carbomer': {
    ingredient_name: 'Carbomer (Carbopol)',
    description: 'A synthetic polymer that thickens water-based formulas into clear gels. Must be neutralized to create gel structure.',
    benefits: ['Creates clear gels', 'Excellent thickening', 'Stable across many conditions', 'Lightweight feel'],
    best_for: ['Serums', 'Gel moisturizers', 'Hand gels', 'Oil-free products'],
    usage_rate: '0.3–2%',
    category: 'Thickener / Gelling Agent',
    ph_notes: 'Must be neutralized with sodium hydroxide or triethanolamine to pH 5–7 to activate gel.',
    cautions: 'Forms white gluey clumps if not dispersed properly — add slowly to water with agitation.',
  },
  'geogard ultra': {
    ingredient_name: 'Geogard Ultra (Gluconolactone & Sodium Benzoate)',
    description: 'A broad-spectrum preservative blend that is ECOCERT approved. Gentle and effective for water-containing formulas.',
    benefits: ['Broad-spectrum preservation', 'ECOCERT approved', 'Gentle on skin', 'Effective at low usage rates'],
    best_for: ['All water-containing formulas', 'Natural formulations'],
    usage_rate: '0.5–1%',
    category: 'Preservative',
    ph_notes: 'Most effective at pH below 6.',
    cautions: 'Check pH — loses efficacy above pH 6.',
  },
  'optiphen': {
    ingredient_name: 'Optiphen (Phenoxyethanol & Caprylyl Glycol)',
    description: 'A paraben-free preservative blend effective against bacteria and yeast. Does not require specific pH to work.',
    benefits: ['Broad-spectrum preservation', 'Paraben-free', 'pH-flexible', 'Also conditions skin'],
    best_for: ['Lotions', 'Creams', 'Cleansers'],
    usage_rate: '0.75–1.5%',
    category: 'Preservative',
    ph_notes: 'Effective across a broad pH range — advantage over many preservatives.',
    cautions: 'Some individuals are sensitive to phenoxyethanol.',
  },
  'baking soda': {
    ingredient_name: 'Baking Soda (Sodium Bicarbonate)',
    description: 'A mild alkaline salt used as a deodorizer, pH buffer, and in bath bombs to create fizz with citric acid.',
    benefits: ['Deodorizer', 'Fizz reaction in bath bombs', 'Mild abrasive', 'pH buffer'],
    best_for: ['Bath bombs', 'Laundry deodorizing', 'Cleaning scrubs'],
    usage_rate: '50% in bath bombs (paired with citric acid), 10–30% in laundry',
    category: 'Alkaline Buffer / Deodorizer',
    ph_notes: 'Mildly alkaline — pH around 8.3.',
    cautions: 'Not suitable as a skin deodorant long-term — can disrupt skin pH.',
  },
  'borax': {
    ingredient_name: 'Borax (Sodium Tetraborate)',
    description: 'A naturally occurring mineral salt used as a laundry booster, emulsifier, and cleaning agent.',
    benefits: ['Boosts cleaning power', 'Softens water', 'Antimold properties', 'Can act as emulsifier with beeswax'],
    best_for: ['Laundry boosting', 'Household cleaners', 'DIY beeswax emulsions'],
    usage_rate: '5–20% in laundry, small amounts in DIY emulsions',
    category: 'Cleaning Booster / Mineral Salt',
    ph_notes: 'Alkaline in solution.',
    cautions: 'Irritating to eyes and skin in high concentrations. Avoid inhaling. Do not use in baby products.',
  },
  'olive oil': {
    ingredient_name: 'Olive Oil',
    description: 'A traditional skin and soap-making oil pressed from olives. High in oleic acid, very nourishing but heavy.',
    benefits: ['Deeply nourishing', 'Anti-inflammatory', 'Creates conditioning soap bar', 'Rich in antioxidants'],
    best_for: ['Cold process soap', 'Rich body butters', 'Very dry skin', 'Hair treatments'],
    usage_rate: '10–72% in soap, 2–20% in skin products',
    category: 'Emollient',
    ph_notes: null,
    cautions: 'Heavy and greasy feel in high amounts on skin. Creates soft soap bars — combine with coconut oil for harder bars.',
  },
  'palm oil': {
    ingredient_name: 'Palm Oil',
    description: 'A saturated fat from the fruit of oil palms. Used in soap making to create hard bars with stable lather.',
    benefits: ['Creates hard soap bars', 'Stable conditioning lather', 'Widely available'],
    best_for: ['Cold process soap making'],
    usage_rate: '20–40% in soap',
    category: 'Soap Hardener / Emollient',
    ph_notes: null,
    cautions: 'Sustainability concerns — look for RSPO certified. Not for use in leave-on skin products.',
  },
  'lye': {
    ingredient_name: 'Lye (Sodium Hydroxide / NaOH)',
    description: 'A strongly alkaline compound used in cold process soap making. Reacts with oils in saponification to create soap — no lye remains in finished soap.',
    benefits: ['Essential for cold process soap', 'Creates true soap via saponification'],
    best_for: ['Cold process bar soap', 'Shampoo bars'],
    usage_rate: 'Calculated exactly per oil weight using a lye calculator',
    category: 'Saponification Agent',
    ph_notes: 'Extremely alkaline — pH 14.',
    cautions: 'DANGEROUS — causes severe burns. Always add lye to water, never water to lye. Wear gloves, goggles, and long sleeves. Store safely away from children.',
  },
  'potassium hydroxide': {
    ingredient_name: 'Potassium Hydroxide (KOH)',
    description: 'An alkali used to make liquid soap and shampoos via saponification. Creates soft or liquid soap rather than hard bars.',
    benefits: ['Makes liquid soap and shampoo bars', 'Saponifies oils fully'],
    best_for: ['Liquid soap', 'Shampoo bars', 'Soft soap'],
    usage_rate: 'Calculated exactly per oil weight using a lye calculator (use KOH values)',
    category: 'Saponification Agent',
    ph_notes: 'Extremely alkaline.',
    cautions: 'DANGEROUS — causes severe burns. Same safety precautions as sodium hydroxide.',
  },
  'cocoa butter': {
    ingredient_name: 'Cocoa Butter',
    description: 'A solid fat extracted from cocoa beans. Melts at body temperature and creates a protective layer on skin with a light chocolate scent.',
    benefits: ['Deep moisturizing', 'Creates protective barrier', 'Firms and hardens formulas', 'Light natural scent'],
    best_for: ['Body butters', 'Lip balms', 'Lotion bars', 'Stretch mark prevention'],
    usage_rate: '5–100%',
    category: 'Occlusive / Emollient',
    ph_notes: null,
    cautions: 'Can feel heavy — blend with lighter butters or oils. May clog pores for acne-prone skin.',
  },
  'mango butter': {
    ingredient_name: 'Mango Butter',
    description: 'A semi-solid fat extracted from mango seeds. Lighter than shea or cocoa butter with excellent skin conditioning properties.',
    benefits: ['Moisturizing', 'Lighter than cocoa butter', 'Anti-inflammatory', 'Protects skin barrier'],
    best_for: ['Body butters', 'Lotions', 'Hair care', 'Sunscreen bases'],
    usage_rate: '2–25%',
    category: 'Emollient / Occlusive',
    ph_notes: null,
    cautions: null,
  },
  'polysorbate 80': {
    ingredient_name: 'Polysorbate 80',
    description: 'A versatile emulsifier and solubilizer derived from sorbitol and oleic acid. Helps disperse oils in water-based formulas.',
    benefits: ['Solubilizes oils in water', 'Stabilizes emulsions', 'Helps fragrance oils disperse in bath products'],
    best_for: ['Bath oils', 'Toners with oils', 'Fragrance solubilizing', 'Emulsions'],
    usage_rate: '1–10% depending on application',
    category: 'Emulsifier / Solubilizer',
    ph_notes: null,
    cautions: 'Some concerns about skin penetration enhancement — use at recommended levels.',
  },
  'sodium lactate': {
    ingredient_name: 'Sodium Lactate',
    description: 'The sodium salt of lactic acid. Used in soap making to speed unmolding, and in skin care as a humectant.',
    benefits: ['Speeds soap unmolding', 'Humectant in skin care', 'Creates harder soap bars', 'Improves lather'],
    best_for: ['Cold process soap', 'Lotions and serums'],
    usage_rate: '1–3% in skin care, 1 tsp per pound of oils in soap',
    category: 'Humectant / Soap Additive',
    ph_notes: null,
    cautions: null,
  },
  'dl-panthenol': {
    ingredient_name: 'DL-Panthenol (Vitamin B5)',
    description: 'Identical to panthenol — the racemic mixture form widely used in hair and skin products for moisturizing and repair.',
    benefits: ['Moisturizing', 'Repairs damaged hair', 'Reduces inflammation', 'Improves skin elasticity'],
    best_for: ['Shampoos', 'Conditioners', 'Leave-in hair products', 'Lotions'],
    usage_rate: '0.5–5%',
    category: 'Humectant / Hair Conditioning Agent',
    ph_notes: 'Stable pH 4–7.',
    cautions: null,
  },
  'silk amino acids': {
    ingredient_name: 'Silk Amino Acids',
    description: 'Hydrolyzed silk proteins broken into small amino acids. Penetrate hair and skin to add moisture, strength, and shine.',
    benefits: ['Adds shine to hair', 'Strengthens hair', 'Moisturizes skin', 'Improves skin texture'],
    best_for: ['Shampoos', 'Conditioners', 'Serums', 'Facial toners'],
    usage_rate: '1–5%',
    category: 'Protein / Conditioning Agent',
    ph_notes: null,
    cautions: null,
  },
  'arrowroot powder': {
    ingredient_name: 'Arrowroot Powder',
    description: 'A starch derived from arrowroot plants. Used to create silky textures, absorb excess oil, and as a talc alternative.',
    benefits: ['Absorbs excess oil', 'Creates silky skin feel', 'Talc-free alternative', 'Thickens formulas'],
    best_for: ['Dry shampoo', 'Setting powder', 'Deodorant powder', 'Body powder'],
    usage_rate: '5–50% in powders',
    category: 'Absorbent / Texture Agent',
    ph_notes: null,
    cautions: null,
  },
  'kaolin clay': {
    ingredient_name: 'Kaolin Clay (White Clay)',
    description: 'The mildest cosmetic clay. Gently cleanses, absorbs oil, and detoxifies skin without over-drying.',
    benefits: ['Gentle cleansing', 'Oil absorption', 'Detoxifying', 'Good for sensitive skin'],
    best_for: ['Face masks', 'Sensitive skin', 'Gentle cleansers', 'Dry shampoo'],
    usage_rate: '5–50% in masks',
    category: 'Clay / Absorbent',
    ph_notes: 'pH around 6–7.',
    cautions: 'Mildest clay — suitable even for dry or sensitive skin.',
  },
  'bentonite clay': {
    ingredient_name: 'Bentonite Clay',
    description: 'A swelling clay formed from volcanic ash. Highly absorbent and detoxifying, draws out impurities from pores.',
    benefits: ['Deep pore cleansing', 'Removes toxins', 'Antibacterial', 'Strong oil absorption'],
    best_for: ['Oily skin', 'Acne-prone skin', 'Deep cleansing masks', 'Detox formulas'],
    usage_rate: '5–25% in masks',
    category: 'Clay / Deep Cleanser',
    ph_notes: 'pH around 8–10 when hydrated.',
    cautions: 'Too drying for dry or sensitive skin. Do not use metal utensils — can reduce effectiveness.',
  },
  'distilled water': {
    ingredient_name: 'Distilled Water',
    description: 'Water purified by distillation to remove minerals and contaminants. Essential as the water phase base in emulsions.',
    benefits: ['Pure water phase', 'No minerals to interfere with formula', 'Prevents contamination'],
    best_for: ['All water-containing formulas'],
    usage_rate: 'Makes up water phase — often 50–80% of lotion/cream formulas',
    category: 'Water Phase Base',
    ph_notes: 'pH 7 (neutral).',
    cautions: 'Never use tap water in formulas — minerals and bacteria will compromise the product.',
  },
};
